name: Server Autofix (SKM)
on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "fixes/**"
      - ".github/workflows/**"
jobs:
  apply:
    runs-on: [self-hosted, linux, skm, autofix]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run SKM fixes
        env:
          DOMAIN: cloud.skmatcloud.com
        run: bash fixes/apply.sh
      - name: Tail last autofix log (debug)
        run: |
          ls -lt /var/log/skm-autofix | head -n 5 2>/dev/null || true
          lastlog="$(ls -1t /var/log/skm-autofix/*.log 2>/dev/null | head -n1 || true)"
          [ -n "$lastlog" ] && tail -n 120 "$lastlog" || true
