name: Server Autofix (SKM)

on:
  push:
    branches: [ "main" ]
    paths:
      - "fixes/**"
      - ".github/workflows/**"

jobs:
  apply:
    runs-on: [self-hosted, linux, skm, autofix]
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SKM fixes
        run: bash fixes/apply.sh
