name: Server Autofix (SKM)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "fixes/**"
      - ".github/workflows/server-autofix.yml"

jobs:
  apply:
    runs-on: [self-hosted, linux, skm, autofix]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run auto-fix
        shell: bash
        run: |
          set -euo pipefail
          bash fixes/apply.sh
